version: '3.8'

services:
  # 1. The Database (Stores the data permanently)
  postgres:
    image: postgres:16
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      # This folder 'keycloak_data' will appear on your PC next to this file
      - ./keycloak_data:/var/lib/postgresql/data

  # 2. Keycloak (Connects to the database)
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak_26
    command: start-dev
    environment:
      # CONNECT TO POSTGRES instead of dev-mem
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      
      # Admin Credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      - postgres