version: '3.8'

services:
  # 1. The Database (Stores the data permanently)
  postgres:
    image: postgres:16
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      # This folder 'keycloak_data' will appear on your PC next to this file
      - ./keycloak_data:/var/lib/postgresql/data

  # 2. Keycloak (Connects to the database)
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak_26
    command: start-dev
    environment:
      # CONNECT TO POSTGRES instead of dev-mem
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      
      # Les identifiants admin ont été retirés pour la sécurité.
      # Utilise le compte admin créé manuellement via l'interface.

      # --- AJOUTER CECI POUR LE PREMIER DÉMARRAGE ---
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "8180:8080"
    depends_on:
      - postgres

  # --- AJOUT DU SERVICE IA ---
  ai_service:
    container_name: burnout_ai
    build:
      context: ../ai_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Accessible via http://localhost:8000
    volumes:
      # Synchronisation : Si tu changes ton code sur Windows,
      # ça se met à jour dans Docker immédiatement.
      - ../ai_service:/app
      # On ignore les fichiers lourds ou inutiles pour éviter de les copier en boucle
      - /app/__pycache__
      - /app/dataset
      - /app/models
    environment:
      - PYTHONUNBUFFERED=1